baseurl = "http://open-canalyzer.github.io/docs"
languageCode = "en-us"
title = "Open-Canalyzer Docs"
theme = "hugo-theme-learn"
canonifyurls = true

[params]
  editURL = "https://github.com/Open-Canalyzer/docs"
  description = "Documentation for the Open-Canalyzer"
  author = "Maarten Tamboer and Jerry Jacobs"
