baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-learn"

[params]
  editURL = "https://github.com/Open-Canalyzer/docs"
  description = "Documentation for the Open-Canalyzer"
  author = "Maarten Tamboer and Jerry Jacobs"